### ISSUE TITLE
Are there any plans to update this project?

### ISSUE THREAD

**Issue by Noksa** [pascomnet/kamailio_exporter#3]
It is out of date and can't work with kamailio 5.1.x

**Comment by towe75** [comment]
Kamailio did not change the API calls/interface that we're using and the exporter works still correctly with Kamailio 5.3.x and also 5.4.x in our productive systems.
 
There are, however, no plans to continue this project because Kamailio has got a native module for the same purpose since a while, see announcement at https://www.kamailio.org/w/2019/06/new-module-xhttp_prom/

**Comment by Noksa** [comment]
Yeah, sorry. I meant 5.0.x. 

This project works only with 5.1.x, right?

Anyway thanks!

**Comment by towe75** [comment]
We never tested it on ancient versions, sorry. It was coded 2019 and Kamailio 5.1.0 was released 12/2017.

**Comment by emmceemoore** [comment]
> There are, however, no plans to continue this project because Kamailio has got a native module for the same purpose since a while, see announcement at https://www.kamailio.org/w/2019/06/new-module-xhttp_prom/

I was excited to try out the `xhttp_prom` module. I gave it a try and it didn't work out for my needs, unfortunately, because of [this issue](https://github.com/kamailio/kamailio/issues/3001).

I hope you do continue with this project. I've found it to be useful. Thanks!

**Comment by towe75** [comment]
@emmceemoore Thank you for the positive feedback!

We're still using it internally and actually pushed a few new features recently. There are, for now, no plans to give it up. We looked at xhttp_prom but it was to limit for our use cases. It would certainly better to contribute directly there but maintaining this sidecar binary is much simpler for us.
